"""Add fundamentals table and last_fetched_at

Revision ID: 37f6ebc71508
Revises: c3cfe642496a
Create Date: 2026-04-14 10:40:21.885229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37f6ebc71508'
down_revision: Union[str, Sequence[str], None] = 'c3cfe642496a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_fundamentals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('pe_ratio', sa.Float(), nullable=True),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('dividend_yield', sa.Float(), nullable=True),
    sa.Column('week_52_high', sa.Float(), nullable=True),
    sa.Column('week_52_low', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_fundamentals_id'), 'stock_fundamentals', ['id'], unique=False)
    op.create_index(op.f('ix_stock_fundamentals_symbol'), 'stock_fundamentals', ['symbol'], unique=True)
    op.add_column('earnings_dates', sa.Column('last_fetched_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('earnings_dates', 'last_fetched_at')
    op.drop_index(op.f('ix_stock_fundamentals_symbol'), table_name='stock_fundamentals')
    op.drop_index(op.f('ix_stock_fundamentals_id'), table_name='stock_fundamentals')
    op.drop_table('stock_fundamentals')
    # ### end Alembic commands ###
